FROM python:slim-bullseye

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY ./requirements.txt /app/requirements.txt

# Install the requirements
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

# Copy the application files
COPY . /app

ENTRYPOINT [ "python3" ]

# Start the application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main:app"]